# Spring Settings
spring:
  application:
    name: '@project.name@'

  # Database
  datasource:
    url: jdbc:h2:mem:pricedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=VALUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  # Jpa
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

# OpenApi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /api-docs

# Info application
info:
  application:
    description: '@project.description@'
    version: '@project.version@'
  architecture: '@project.parent.version@'

logging:
  level:
    org.springframework.boot.autoconfigure.h2: DEBUG
