# Spring Settings
spring:
  application:
    name: demo

  # Database
  datasource:
    url: jdbc:h2:mem:pricedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  # Sql
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

  # Jpa
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true



  # H2
  h2:
    console:
      enabled: true

# OpenApi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /api-docs

# Logging
logging:
  level:
    liquibase: DEBUG
    org.liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG

